name: Deploy to Stage Test on Branch Main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
      MEX_SERVICE_REFRESH_TOKEN: ${{ secrets.MEX_SERVICE_REFRESH_TOKEN }}
      MEX_SERVICE_CLIENT_ID: ${{ secrets.MEX_SERVICE_CLIENT_ID }}
      REDIRECT_HOST: ${{ secrets.REDIRECT_HOST }}
      MEXIT_MIDDLEWARE_IP: ${{ secrets.MEXIT_MIDDLEWARE_IP }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@workduck-io'
      - run: npm install -g yarn
      - name: Create .env file
        run: |
          touch .env
          echo YARN_TOKEN=${{ secrets.YARN_TOKEN }} >> .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} >> .env
          echo SLACK_CLIENT_ID=${{ secrets.SLACK_CLIENT_ID }} >> .env
          echo SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} >> .env
          echo SLACK_CLIENT_SECRET=${{ secrets.SLACK_CLIENT_SECRET }} >> .env
          echo MEX_SERVICE_REFRESH_TOKEN=${{ secrets.MEX_SERVICE_REFRESH_TOKEN }} >> .env
          echo MEX_SERVICE_CLIENT_ID=${{ secrets.MEX_SERVICE_CLIENT_ID }} >> .env
          echo REDIRECT_HOST=${{ secrets.REDIRECT_HOST }} >> .env
          echo MEXIT_MIDDLEWARE_IP=${{ secrets.MEXIT_MIDDLEWARE_IP }} >> .env
      - run: yarn
      - run: yarn sls deploy --stage=test
