name: Deploy to Stage Test on Branch Main
on:
  push:
    branches:
      - main
      - mukul-wd-1352-task-github-actions-for-automated

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YARN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
      SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
      MEX_SERVICE_REFRESH_TOKEN: ${{ secrets.MEX_SERVICE_REFRESH_TOKEN }}
      MEX_SERVICE_CLIENT_ID: ${{ secrets.MEX_SERVICE_CLIENT_ID }}
      REDIRECT_HOST: ${{ secrets.REDIRECT_HOST }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: "16.x"
      - run: npm install -g yarn
      - run: yarn --no-default-rc
      - run: yarn sls deploy --stage=test
